on: push
name: Build and deploy on push
jobs:
  build:
    name: Build with Zola and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Deploy to Github Pages
      uses: shalzz/zola-deploy-action@master
      env:
        PAGES_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: ipfs/ipfs-deploy-action@v1
      name: Deploy to IPFS
      id: deploy
      with:
        path-to-deploy: public
        storacha-key: ${{ secrets.STORACHA_KEY }}
        storacha-proof: ${{ secrets.STORACHA_PROOF }}
        github-token: ${{ github.token }}

    - uses: ipfs/dnslink-action@v0.1
      if: github.ref == 'refs/heads/zola' # only update the DNSLink on the main branch
      name: Update DNSLink
      with:
        cid: ${{ steps.deploy.outputs.cid }} # The CID of the build to update the DNSLink for
        dnslink_domain: shaleenjain.com
        cf_record_id: ${{ secrets.CF_RECORD_ID }}
        cf_zone_id: ${{ secrets.CF_ZONE_ID }}
        cf_auth_token: ${{ secrets.CF_AUTH_TOKEN }}
        github-token: ${{ github.token }}
