on: push
name: Build and deploy on push
jobs:
  build:
    name: Build with Zola and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Deploy to Github Pages
      uses: shalzz/zola-deploy-action@master
      env:
        PAGES_BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: ipfs/ipfs-deploy-action@v1
      name: Deploy to IPFS
      id: deploy
      with:
        path-to-deploy: public
        storacha-key: ${{ secrets.STORACHA_KEY }}
        storacha-proof: ${{ secrets.STORACHA_PROOF }}
        github-token: ${{ github.token }}
